### ISSUE TITLE
How to become a Transifex reviewer?

### ISSUE THREAD

**Issue by fjorba** [inveniosoftware/troubleshooting#39]
I dear to ask this issue here about Transifex, as I don't see any message in the Transifex Invenio forum.

As I am the only real (the other being @tiborsimko ) Catalan translator, may can I become reviewer?  Otherwise, it seems that I cannot approve the pending translation.

**Comment by lnielsen** [comment]
I've changed your role to "coordinator" for both Catalan and Spanish. This allows you in addition to reviewing to also invite others to the Catalan and Spanish teams.

**Comment by fjorba** [comment]
Great, thanks so much!
