### ISSUE TITLE
May I see other language translations in Transifex?

### ISSUE THREAD

**Issue by fjorba** [inveniosoftware/troubleshooting#40]
Sometimes, when translating, I'd like to see how similar languages have resolved a text.  For that, in Invenio, usually I check French, Spanish, Italian or Portuguese translations.

Previously, when working with .po files with Emacs, that was quite easy.  Now, in Transifex, I can only see Spanish, being myself part of the team.

How can I switch to the other languages, obviously in readonly mode?  Or, my I became a readonly team member of those translation teams?

**Comment by lnielsen** [comment]
I've added you as a translator for the requested teams. 

You should be able to click on first a language, and then a resource, and then last the "View strings online" for language for which you are not a translator.

![screen shot 2018-08-14 at 14 49 18](https://user-images.githubusercontent.com/1698163/44092684-82008204-9fd1-11e8-914f-a27873e6ff35.png)

Note: you'll probably see the "Translate" button greyed out.

**Comment by fjorba** [comment]
Thanks, comparing the translations is a must!
